- frontend/README.md
- frontend/package-lock.json
- frontend/package.json
This is a combination of things Gail said, and what I found I needed from looking online.
> Add some Angular setup instructions to the README.md

- README.md
This is far from perfect, but it will help get folks started.
> Blow some setup instructions into the README

- frontend/src/app/_components/button/button.component.html
- frontend/src/app/_components/button/button.component.spec.ts
- frontend/src/app/_components/button/button.component.ts
- frontend/src/app/_components/index.ts
- frontend/src/app/_components/shared.module.ts
- frontend/src/app/_helpers/auth.guard.spec.ts
- frontend/src/app/_helpers/auth.guard.ts
- frontend/src/app/_helpers/index.ts
- frontend/src/app/_services/account.service.spec.ts
- frontend/src/app/_services/account.service.ts
- frontend/src/app/_services/index.ts
- frontend/src/app/account/account-routing.module.ts
- frontend/src/app/account/account.module.ts
- frontend/src/app/account/layout/layout.component.html
- frontend/src/app/account/layout/layout.component.spec.ts
- frontend/src/app/account/layout/layout.component.ts
- frontend/src/app/account/login/login.component.html
- frontend/src/app/account/login/login.component.spec.ts
- frontend/src/app/account/login/login.component.ts
- frontend/src/app/app-routing.module.ts
- frontend/src/app/app.component.html
- frontend/src/app/app.module.ts
- frontend/src/app/landing/landing.component.html
- frontend/src/app/landing/landing.component.spec.ts
- frontend/src/app/landing/landing.component.ts
- frontend/tsconfig.json
login basics - note this does not include new server endpoint.
> Login Skeleton

- frontend/src/app/schedule/filters/filters.component.html
- frontend/src/app/schedule/filters/filters.component.scss
- frontend/src/app/schedule/item/item.component.html
- frontend/src/app/schedule/item/item.component.ts
- frontend/src/app/schedule/program/program.component.html
- frontend/src/app/schedule/program/program.component.scss
otherwise known as: my sister is the best
> Feature better schedule

- frontend/src/app/_components/breadcrumb/breadcrumb.component.ts
- frontend/src/app/_models/program_filter.ts
- frontend/src/app/_models/program_item.ts
- frontend/src/app/_models/program_person.ts
- frontend/src/app/_services/account.service.ts
- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/account/login/login.component.ts
- frontend/src/app/landing/landing.component.html
- frontend/src/app/landing/landing.component.ts
- frontend/src/app/map/featured-events/featured-events.component.ts
- frontend/src/app/schedule/filters/filters.component.html
- frontend/src/app/schedule/filters/filters.component.ts
- frontend/src/app/schedule/item/item.component.ts
- frontend/src/app/schedule/people/people.component.ts
- frontend/src/app/schedule/person/person.component.html
- frontend/src/app/schedule/person/person.component.ts
- frontend/src/app/schedule/program/program.component.ts
- frontend/tsconfig.json
Changed the meaning of ProgramFilters to allow for empty lists meaning
no filters, but they're still optional.
Changed how filters work instead of iterating over filter keys.
Added else cases for some data that might not be loaded by the time they're displayed.
Various other small fixes.
> Switch to strict compilation and fix type errors.

- frontend/src/app/app.module.ts
- frontend/src/app/infodesk/infodesk.component.html
- frontend/src/app/infodesk/infodesk.component.spec.ts
- frontend/src/app/infodesk/infodesk.component.ts
- frontend/src/app/irt/irt.component.html
- frontend/src/app/irt/irt.component.scss
- frontend/src/app/irt/irt.component.spec.ts
- frontend/src/app/irt/irt.component.ts
- frontend/src/app/map/map.component.html
- frontend/src/app/map/map.component.ts
- frontend/src/app/safety/safety.component.html
- frontend/src/app/safety/safety.component.scss
- frontend/src/app/safety/safety.component.spec.ts
- frontend/src/app/safety/safety.component.ts
Adds Infodesk, Irt, and Safety components and then uses them as modal dialogs in Map component.
Desktop Screenshot
Mobile Screenshot
> Add Modal popups for clicking on rounded map nodes.

- frontend/src/app/map/map.component.html
Somehow I missed this line when doing a merge.
> Fix accidental incomplete merge.

- frontend/src/app/app.module.ts
These components were lost from the app module during git merging somehow.
> Fix missing components in app.module.ts.

- arisia-remote/app/arisia/models/ProgramItem.scala
Realized that the Schedule was using the Java 1 Date type; changed that to the Java 8 LocalDate, which will work better for what we need to do with it.
> Switch to the correct Date type

- frontend/src/app/map/hall-costumes/hall-costumes.component.html
- frontend/src/app/map/hall-costumes/hall-costumes.component.scss
- frontend/src/styles.scss
Add border.
Scale Image to fit centered within the box.
Make the gradient overlay not steal clicks.
Add a black background to the box.
Update the alt text to refer to the fact that it's a picture.
> Polish Hall costume component.

- frontend/src/app/_models/program_filter.ts
- frontend/src/app/_models/program_item.ts
- frontend/src/app/_models/program_person.ts
- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/map/featured-events/featured-events.component.html
- frontend/src/app/map/featured-events/featured-events.component.ts
- frontend/src/app/schedule/filters/filters.component.html
- frontend/src/app/schedule/filters/filters.component.ts
- frontend/src/app/schedule/item-list/item-list.component.html
- frontend/src/app/schedule/item-list/item-list.component.ts
- frontend/src/app/schedule/item/item.component.html
- frontend/src/app/schedule/item/item.component.ts
- frontend/src/app/schedule/people/people.component.html
- frontend/src/app/schedule/people/people.component.ts
- frontend/src/app/schedule/person/person.component.html
- frontend/src/app/schedule/person/person.component.ts
- frontend/src/app/schedule/program/program.component.html
- frontend/src/app/schedule/program/program.component.ts
It creates new classes for ScheduleEvent and SchedulePerson.
In particular, this creates links between events and people.
It also parses the timeStamp string and uses that to create a Date
object for events.
It creates a new StructuredEvents type that is list based instead of
object based.  This object is created by sorting the events and then
partitioning them based on Date.
It changes date filters to be based on Date objects instead of
comparing to date string. This will allow us to search by current time
as well as day of the week. It also means date filters will be based
on current time zone.
> Process schedule data into a form that is more usable.

- frontend/src/app/_components/settings/settings.component.html
- frontend/src/app/_components/settings/settings.component.spec.ts
- frontend/src/app/_components/settings/settings.component.ts
- frontend/src/app/_components/shared.module.ts
- frontend/src/app/_models/program_filter.ts
- frontend/src/app/_services/index.ts
- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/_services/settings.service.spec.ts
- frontend/src/app/_services/settings.service.ts
- frontend/src/app/app.component.html
- frontend/src/app/schedule/filters/filters.component.html
- frontend/src/app/schedule/filters/filters.component.ts
- frontend/src/app/schedule/person/person.component.html
This allows switching between 24 and 12 hour time.
It allows setting a time offset override in order to test the new Now filter.
> Adds a settings service and uses it in various places.

- frontend/src/app/app.component.html
changed "farily" to "fairly" for the main footer
> Fix a typo

- frontend/src/app/_components/settings/settings.component.html
- frontend/src/app/_components/settings/settings.component.scss
- frontend/src/app/_components/settings/settings.component.ts
- frontend/src/app/_components/shared.module.ts
- frontend/src/app/_services/settings.service.ts
Also lays out settings component with flex box.
> Add date and time pickers for time offset to make testing easier.

- arisia-remote/app/arisia/auth/CMService.scala
Yeah, I knew this was going to give me trouble. Getting weird errors when I try to run this on production; looking at it, found two stupid errors. Let's fix those.
> Fix stupid SQL errors

- arisia-remote/app/arisia/auth/CMService.scala
This is a temporary hack, to get more information while trying to figure out why the SQL query isn't working.
> Add statement logging

- arisia-remote/app/arisia/auth/CMService.scala
Not sure this will help, but let's give it a try.
> Try to get more logging

- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/programming/programming.component.html
- frontend/src/app/programming/programming.component.scss
- frontend/src/app/programming/programming.component.ts
Updates the programming UI to better match the specs and updated the code to generate the running and next events to update live over time.
> Programming

- arisia-remote/app/arisia/controllers/DiscordController.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/conf/routes
- build.sbt
This doesn't actually *do* anything yet, but it's the expected API so that Gail can try coding against it and confirm that it matches expectations.
@Gailbear
> Provide API entry point for adding an Arisian

- arisia-remote/app/arisia/admin/RoomService.scala
- arisia-remote/app/arisia/controllers/DuckController.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/fun/DuckService.scala
- arisia-remote/app/arisia/views/manageDucks.scala.html
- arisia-remote/app/arisia/views/manageZoomRooms.scala.html
- arisia-remote/conf/routes
* Makes Ducks editable
* Makes Ducks deletable
* Makes Rooms deletable
Fixed #307
> Finish CRUD

- frontend/src/app/account/login/login.component.html
- frontend/src/app/account/login/login.component.scss
- frontend/src/app/account/login/login.component.ts
Shows login errors.
Added message about password matching reg.
Fixed the white background on the log in button.
Made it so text is never overlapping when resizing.
> Login fixes

- arisia-remote/app/arisia/views/adminHome.scala.html
Shouldn't be necessary, but people are a problem.
Fixes #143
> Put a warning on the Admin homepage to not be a jerk

- frontend/src/app/_components/alphabet-links/alphabet-links.component.ts
- frontend/src/app/programming/room/room.component.html
- frontend/src/app/schedule/item/item.component.html
- frontend/src/app/schedule/people/people.component.html
- frontend/src/app/schedule/person-page/person-page.component.html
- frontend/src/app/schedule/person-page/person-page.component.spec.ts
- frontend/src/app/schedule/person-page/person-page.component.ts
- frontend/src/app/schedule/person/person.component.html
- frontend/src/app/schedule/person/person.component.ts
- frontend/src/app/schedule/schedule-routing.module.ts
- frontend/src/app/schedule/schedule.module.ts
Also adds links to participant pages as is appropriate.
> Change how people search URLs work and add individual participant pages.

- arisia-remote/app/arisia/controllers/DiscordController.scala
Lambda really needs everything to go fast, and doesn't care much about the result. So stuff the queries into Futures, and return immediately.
> Make the Lambda entry points fire-and-forget

- arisia-remote/app/arisia/auth/MembershipType.scala
This type is being used for the Zoom captioners.
> Add PaidWorkerComp as a MembershipType

- frontend/src/app/account/login/login.component.html
- frontend/src/app/account/login/login.component.scss
- frontend/src/app/account/login/login.component.ts
> Add You're Early! to login screen.

- frontend/src/app/_components/door-dragon/door-dragon.component.html
- frontend/src/app/_components/door-dragon/door-dragon.component.scss
- frontend/src/app/_components/door-dragon/door-dragon.component.ts
- frontend/src/app/_components/persistent-room-link.directive.spec.ts
- frontend/src/app/_components/persistent-room-link.directive.ts
- frontend/src/app/_components/shared.module.ts
- frontend/src/app/_services/index.ts
- frontend/src/app/_services/zoom-rooms.service.spec.ts
- frontend/src/app/_services/zoom-rooms.service.ts
- frontend/src/app/account/login/login.component.html
- frontend/src/app/account/login/login.component.scss
- frontend/src/app/social/social.component.html
- frontend/src/app/social/social.component.scss
Adds Persistent room links.
Updates login page.
Updates door dragon.
> Add Persistent Room links and update login page.

- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
> Guard against attempts to re-grab Discord accounts.

- frontend/src/app/help/help.component.html
clarified something I had written that is different in dark and light modes
> small tweak to Discord language

- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
They had been using the title of the prep sessions.
> Fix the title of the Zoom meetings

- frontend/src/app/_models/program_filter.ts
- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/schedule/filters/filters.component.html
- frontend/src/app/schedule/filters/filters.component.scss
- frontend/src/app/schedule/filters/filters.component.ts
- frontend/src/app/schedule/item/item.component.html
- frontend/src/app/schedule/item/item.component.ts
> Add captioned and featured filters to schedule

- frontend/src/app/social/social.component.html
turns out that isn't where teen lounge goes
> removed tween lounge from breakout rooms list

- frontend/src/app/_components/settings/settings.component.html
- frontend/src/app/_components/settings/settings.component.scss
- frontend/src/app/_components/settings/settings.component.ts
- frontend/src/app/app-routing.module.ts
- frontend/src/app/discord/discord.component.html
- frontend/src/app/discord/discord.component.scss
- frontend/src/app/navigation/navigation.component.html
- frontend/src/app/user/user.component.html
- frontend/src/app/user/user.component.scss
> Update User settings and kill Landing page.

- frontend/src/app/infodesk/infodesk.component.html
Get rid of FixMe note, add Info docs link, add link to Discord and note about Discord channel name.
> Help Desk popup fixes

- frontend/src/app/_services/index.ts
- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/performance/performance.component.html
- frontend/src/app/performance/performance.component.scss
- frontend/src/app/performance/performance.component.ts
Starts videos at the scheduled time instead of when "doorsOpen".
Sets start times of videos.
Sets autoplay correctly.
Autopauses when you click on the open externally link.
Improved appearance when there's nothing playing.
> Fixup performance hall

- frontend/src/app/navigation/navigation-link/navigation-link.component.html
- frontend/src/app/navigation/navigation-link/navigation-link.component.scss
- frontend/src/app/navigation/navigation-link/navigation-link.component.ts
- frontend/src/app/navigation/navigation.component.html
- frontend/src/app/navigation/navigation.component.ts
- frontend/src/app/schedule/layout/layout.component.html
- frontend/src/app/schedule/layout/layout.component.scss
Moves Schedule tabs into the Navigation drop down.
Also fixes schedule tabs layout on smaller desktops.
> Schedule tabs

- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/map/featured-events/featured-events.component.ts
Only show 2 events in featured.
> Small fixes

- frontend/src/app/social/social.component.html
-added teen lounge with a note about teen role so users know it exists
-re-arranged so most important spaces were at the top
> tweaks to Discord list

- frontend/src/app/schedule/item/item.component.html
for when we get the zoom integration working again
> reinstate the links

- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/currentMeetings.scala.html
- arisia-remote/conf/routes
This includes the meeting URLs, so that Admins can get to them directly if need be.
Fixes #443
> Provide a UI to examine the meetings that the server thinks are running.

- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
We've been observing that most meetings are *not* auto-stopping correctly. My theory is that I got too clever, and the SortedSet that has been acting as a queue for that stuff is getting confused by the fact that there are many items with the same end time.
So let's just drop that, and brute-force things with the map of currently-running items that we are also maintaining instead. In airy theory, this is less efficient; in reality, there are never more than half a dozen items at a time, so that is totally irrelevant.
For the most part, this just simplifies the code.
Fixes #465 (I hope)
> Simplify meeting-end

- frontend/src/app/_components/creator-page/creator-page.component.html
- frontend/src/app/_components/creator-page/creator-page.component.ts
- frontend/src/app/artshow/artist/artist.component.html
- frontend/src/app/artshow/artist/artist.component.ts
This seems a small enough change that I'm not sure it's worth putting in while the site is live. Feel free to reject this pull request.
> Change Artshow => Art Show in artist breadcrumbs.
