ArisiaInc/a21-remote-site

- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/conf/routes
Nothing fancy here: just call it, and get logged out
Also, moved the login and logout entry points under the path `/api/`, which we will use from here on out for all of the API stuff.
> #61 - add a logout entry point

- arisia-remote/app/arisia/PlayComponents.scala
- arisia-remote/app/arisia/auth/LoginService.scala
Two fixes here:
* The PlayComponents need to explicitly enable the CORSFilter.
* The frontend is sending a lower-case "joe", and the backend is expecting capitalized. Trivial to fix that here.
These changes have been tested against the "cors" branch of the frontend, so I believe that rebasing to here should fix it.
> Get login working on the backend

- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/models/LoginUser.scala
On success, returns
```
{"id":"...","name":"..."}
```
In reality, we expect the "id" to be badge number and the "name" to be badge name, once everything is hooked together. For now, it's dummy data.
On failure, returns
```
{"success":"false","message":"..."}
```
> Return a real user-info data structure from the /api/login endpoint

- frontend/package.json
- project/FrontendRunHook.scala
We don't need to *serve* from Angular per se, but we want to have the compiler running and watching for changes, so that it can hot-update when the code changes.
> Run the Angular builder in the background while the backend is running

- arisia-remote/app/arisia/controllers/FrontendController.scala
This should reduce unnecessary reloads, by adding ETags to all of the frontend components being proxied by the backend. With everything signed this way, the browser will version-check stuff before loading it, and only reload if the signature has changed.
> Do proper versioning of the frontend components

- README.md
- arisia-remote/README.md
- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/PlayComponents.scala
- arisia-remote/app/arisia/auth/AuthModule.scala
- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/FakeZambiaController.scala
- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/db/DBService.scala
- arisia-remote/app/arisia/models/Schedule.scala
- arisia-remote/app/arisia/schedule/ScheduleModule.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/app/arisia/timer/Ticker.scala
- arisia-remote/app/arisia/timer/TimerService.scala
- arisia-remote/conf/evolutions/default/1.sql
- arisia-remote/conf/logback.xml
- arisia-remote/conf/routes
- arisia-remote/test/arisia/models/KonOpasReadSpec.scala
- arisia-remote/test/controllers/ScheduleControllerSpec.scala
- build.sbt
This is a pretty enormous PR, with lots of implications, but the tl;dr is that we are now actually using the database -- just a little tiny bit, but enough to show how to do it.  Also, login is now real, performed against CM.  And the code throughout is now getting much realer.
**Important:** starting with this PR, you *must* have a local Postgres database available, and you must provide its connection URL in the `db.default.url` field in your secrets.conf file!  Without that, the system will fail to boot at start time.  See README.md for details.
Now, into the details of what's new...
For now, we only have one trivial table: the `text_files` table, which contains big blobs like the current Schedule.  Obviously we will need several more tables before everything is ready, but I decided not …
> Start using the database

- arisia-remote/conf/application.conf
- arisia-remote/conf/routes
Currently the frontend and backend assets both need `/assets`, which is causing problems. This moves the Admin UI assets to `/admin/assets`
> Move the path for backend assets

- arisia-remote/app/arisia/admin/AdminService.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/manageAdmins.scala.html
- arisia-remote/app/arisia/views/manageEarlyAccess.scala.html
- arisia-remote/app/arisia/views/managePermissionTemplate.scala.html
- arisia-remote/conf/application.conf
- arisia-remote/conf/routes
- arisia-remote/conf/secrets.conf.template
- arisia-remote/public/javascripts/main.js
This introduces a new configuration flag, `arisia.early.access.only`, which currently defaults to true.  (And which we expect will remain true until somewhere in the last few days before the con starts.)  So long as this is true, only people who explicitly have a new Early Access flag, or who have Admin status, will be allowed to log into the site.
**Important:** this also adds an `arisia.allow.logins` array of strings to the `secrets.conf.template` file.  In your development environment, you should add your own username (that is, your login username from Convention Master, which you used to register for the con) to this array in your own local copy of `secrets.conf`.  That will allow you to log into your own environment.  (Otherwise you'd have to go in and manually enter an entry into …
> Add early access flag

- arisia-remote/app/arisia/controllers/FakeZambiaController.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/conf/evolutions/default/3.sql
Gail got the schedule exporter stood up in Zambia, and changed its export format since we prefer JSON. So this adjusts at our end.
For the moment, I'm still using the 2014 JSONP schedule for testing; that will likely get changed sometime in the near future, as the 2021 Zambia schedule gets into a state that works for us.
> Rework the code to expect the schedule as JSON instead of JSONP

- frontend/src/app/map/hall-costumes/hall-costumes.component.html
- frontend/src/app/map/hall-costumes/hall-costumes.component.scss
- frontend/src/app/map/hall-costumes/hall-costumes.component.spec.ts
- frontend/src/app/map/hall-costumes/hall-costumes.component.ts
- frontend/src/app/map/map.component.html
- frontend/src/app/map/map.module.ts
This carousel works by having an arbitrarily large list of images. It
has a buffer of 3 images and creates a carousel with those three
images. Based on the current image and the current frame of the
carousel, it updates the buffer so that the images on either side of
the current image will be correct.
This allows us to have an arbitrarily large set of images while only
having 3 sets of DOM built at any time. It also only loads the images
when they're the next one to be shown. We can update the size of the
buffer if we want to preload more images. We could even have more
images preloaded ahead than behind.
We can also have a trigger when we're getting close to the currently
loaded set of images to ask for more images. I'm imagining a backend
that returns images in chunks. When we're within …
> Add "Infinite" Image Carousel.

- arisia-remote/app/arisia/controllers/FakeZambiaController.scala
For the moment, we're still using the 2014 Zambia data, but we're massaging it so that it always produces a Schedule that consists of yesterday/today/tomorrow/day-after -- all of the dates are pushed forward to be "now". This will permit us to test what things look like when the site is live day-of.
(Obviously this will eventually have to go behind a switch of some sort, and we'll probably switch over to the real A'21 data sometime soon, but this is a step in the right direction.)
The frontend isn't using this data yet, since it's not fetching the Schedule from the backend -- I'll let the frontend team flip the switch in `schedule.service.ts` when they're comfortable with it.  The only thing I notice broken when I do that is that the Day filter at the top of the Schedule page no longer …
> Adjust the dates in the Schedule to be "now"

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/LoginControllerFuncs.scala
- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/schedule/StarService.scala
- arisia-remote/app/arisia/util/package.scala
- arisia-remote/conf/evolutions/default/4.sql
- arisia-remote/conf/routes
- arisia-remote/conf/swagger.yml
- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
Fixes #150 
This introduces endpoints to add, remove, and fetch "stars" on specific schedule items -- basically, allowing the user to highlight items that they want to keep track of in the schedule.  This matches the stars in the current design.
In order to allow me to test this, this PR also introduces automatic Swagger API-doc generation, and a UI for manually testing the API; this can be found at http://localhost:9000/docs/swagger-ui/index.html?url=/admin/assets/swagger.json
> Add star selections

- arisia-remote/app/arisia/PlayComponents.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/zoom/JwtService.scala
- arisia-remote/app/arisia/zoom/ZoomModule.scala
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/app/arisia/zoom/models/ZoomMeeting.scala
- arisia-remote/app/arisia/zoom/models/ZoomUser.scala
- arisia-remote/app/arisia/zoom/models/package.scala
- arisia-remote/conf/application.conf
- arisia-remote/conf/routes
- arisia-remote/conf/secrets.conf.template
- build.sbt
- project/Dependencies.scala
This is *not* yet full meeting automation -- far from it -- but we've now crossed the critical Rubicon: the backend is capable of starting Zoom meetings.
This adds an Admin endpoint with (intentionally) no UI, to create ad-hoc meetings, for testing all of this. This can basically only be called by Admins from Swagger, and is hard to use, so I don't expect anybody to abuse it.
Being able to do this is *enormously* informative, and may require a tweak or two to our plans, but it's mostly working as expected.
> Beginnings of Zoom Automation

- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/models/Schedule.scala
- build.sbt
- project/Dependencies.scala
This adds an `ETag` header from the getSchedule() endpoint -- an MD5 hash of the current schedule. The frontend should return that in an `If-None-Match` header, and the backend will simply return 304 (Not Modified) in the usual case that nothing has changed.
Note that the HTTP standard expects the hash to be in double quotes in both the `ETag` and `If-None-Match` headers: the backend is expecting that.
This also tweaks things to cache the JSON-serialized form of the Schedule, so we don't have to recompute that on every fetch.
> Make the schedule properly cacheable on the frontend

- arisia-remote/app/arisia/models/ProgramItem.scala
- arisia-remote/app/arisia/models/Schedule.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
In order to reduce the processing effort required on the front end, we are computing ISO-8601 timestamps on the backend, and adding them as a new synthesized field in the Zambia data. The format is, eg, `2020-12-28T01:30:00Z` -- the ISO "Instant" format.
Fixes #157
> Add a `timestamp` field for Program Items

- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/conf/application.conf
- arisia-remote/conf/secrets.conf.template
This finally crosses the line from test data into the actual live Schedule.
Note that the schedule requires a logged-in KonOpas session, so you need a Zambia badge ID and password to do this in your development environment. We have set up a Remote "member" specifically for this automation -- see Justin for the credentials.
Fixes #63
> Fetch the real Schedule from Zambia

- frontend/src/app/_services/schedule.service.ts
- frontend/src/app/schedule/people/people.component.html
- frontend/src/app/schedule/people/people.component.ts
- frontend/src/app/schedule/person/person.component.html
- frontend/src/app/schedule/person/person.component.ts
- frontend/src/app/schedule/program/program.component.html
- frontend/src/app/schedule/program/program.component.ts
Replaced scheduleService.get_data() with
scheduleService.schedule$. schedule$ does nothing until the schedule
is loaded and then fires next every time the schedule autoupdates.
Added scheduleService.status$ that observes the state of the schedule.
Changed get_schedule to return an Observable of a structured set of
program items. This way, the returned observable can send updates as
schedule updates happen instead of completing after going over all the
items.
Added get_person_with_items which returns a ProgramPerson object with
its items filled in and fires next whenever schedule updates happen
(there might be a race condition where it fires twice, once with the
old person data and new items data, and once with all the new data,
but it's eventually correct.)
Changed people.component, …
> Made schedule.service.ts pull from the server and support updating.

- README.md
- arisia-remote/conf/secrets.conf.template
- docker-compose.yml
This means you don't have to maintain your own postgres installation locally!
Instructions are in the readme.
> Add docker as an option for the database configuration

- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/conf/routes
Took a bit of trial and error to figure out the correct way to do this, but it seems to be working.
Still only available to Admins via Swagger.
Improved the error handling of startMeeting() a little.
> The backend can now end Zoom meetings

- arisia-remote/conf/logback.xml
Figured out that the reason we weren't writing anything to `application.log` was that the line to invoke that was commented out in the original template we started from. Uncommenting that sends stuff to the log as expected.
Also, the original template was writing all of the console coloring to the log file, which is silly: it just causes problems there. So reformatted the output-file stuff to read better from the file.
> Fix logging

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/timer/TimeService.scala
- arisia-remote/app/arisia/timer/TimerService.scala
- arisia-remote/conf/application.conf
This is mainly for testability, in the hope that we might have a chance to write unit tests. Let's not hardcode `Instant.now()` all over the place.
Also, made the Timer strobe configurable -- I'm not yet certain what settings we will want in the running site.
> Small tweaks to how we manage time

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/admin/RoomService.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/db/DBService.scala
- arisia-remote/app/arisia/models/ProgramItem.scala
- arisia-remote/app/arisia/models/ZoomRoom.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/app/arisia/timer/TimerService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/editRoom.scala.html
- arisia-remote/app/arisia/views/main.scala.html
- arisia-remote/app/arisia/views/manageAdmins.scala.html
- arisia-remote/app/arisia/views/manageEarlyAccess.scala.html
- arisia-remote/app/arisia/views/manageZoomRooms.scala.html
- arisia-remote/conf/application.conf
- arisia-remote/conf/evolutions/default/5.sql
- arisia-remote/conf/routes
- arisia-remote/public/javascripts/main.js
- build.sbt
- project/Dependencies.scala
Just a checkpoint, but lots of stuff going on here.
This creates the "prep" sessions for each scheduled Zoom item, based on the rules provided by Programming.  These sessions will only be visible on the schedule for people who are supposed to be in those sessions (or at least, have access for some reason).
This sets up the Schedule Queue, which will be used to create the Zoom meetings dynamically when they are supposed to start.
This finally deals with providing a reasonable model for CRUD UIs for Admin: we pull in the DataTables library for displaying stuff, and the play-bootstrap library for editing it.  It all requires a lot more boilerplate than I'd like, but it's probably easier to live with that than to indulge in a research project to improve it.
> Progress towards automated Zoom management

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/PlayComponents.scala
- arisia-remote/app/arisia/admin/AdminService.scala
- arisia-remote/app/arisia/admin/RoomService.scala
- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/general/LifecycleService.scala
- arisia-remote/app/arisia/models/LoginUser.scala
- arisia-remote/app/arisia/models/Permissions.scala
- arisia-remote/app/arisia/models/ProgramItem.scala
- arisia-remote/app/arisia/models/ProgramPerson.scala
- arisia-remote/app/arisia/models/Schedule.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/app/arisia/timer/TimerService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/manageTech.scala.html
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/app/arisia/zoom/models/ZoomMeeting.scala
- arisia-remote/conf/evolutions/default/5.sql
- arisia-remote/conf/routes
This gets Zoom meetings to the point of being mostly right.  The main feature that is missing is the correct handling of Program Participants, which is blocked on getting their badge numbers from CM.  (So I'm going to pivot to working on that next.)
Zoom meetings now get started and stopped based on the schedule.
There is now an entry point for Zoom meetings -- hit this, and if you are a logged-in user, and the meeting has started, it redirects you there.
There is now an Admin UI for managing members of Tech.  They get the `zoomhost` flag, which means that they are potential Zoom hosts.  They therefore get to see the full schedule, including prep sessions, and can enter the prep sessions.
Potential Zoom hosts can now also use the special `zoomhost` variant of the enter-meeting entry …
> Zoom Meetings are now mostly implemented

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/DuckController.scala
- arisia-remote/app/arisia/fun/DuckService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/editDuck.scala.html
- arisia-remote/app/arisia/views/manageDucks.scala.html
- arisia-remote/conf/evolutions/default/6.sql
- arisia-remote/conf/routes
This isn't complete yet, mostly because I'm not sure of the precise desired semantics of the requesting_url. Does this mean the Referrer header of the incoming request? Is it mandatory, or only for some ducks?
Similarly, is the hint text mandatory or optional?
Currently I have both hint and requesting_url as optional, but that's purely a guess -- let's get this right before we merge this.
Regardless of all that, this is a fair template for a new CRUD system.  The main thing that should probably be changed is that too much is landing in the `AdminController` -- we need to start breaking out separate Admin subsystems, to keep that controller from getting entirely unwieldy, and maybe see if we can lift out some common base functions for all the CRUD stuff.
> First draft of the backend for Ducks

- arisia-remote/app/arisia/auth/CMService.scala
The logging isn't getting any better. The problem appears to have to do with the parameterization of the prepared statement, so let's simplify that by hard-coding the constants and being less fancy with the one real parameter.
> Simplify the query

- arisia-remote/app/arisia/auth/CMService.scala
Found a webpage suggesting that you *don't* quote interpolated Strings, so let's try that.
> The quoting may be the problem

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/DuckController.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/controllers/SettingsController.scala
- arisia-remote/app/arisia/controllers/UserFuncs.scala
- arisia-remote/app/arisia/fun/DuckService.scala
- arisia-remote/app/arisia/general/SettingsService.scala
- arisia-remote/conf/evolutions/default/7.sql
- arisia-remote/conf/routes
This is very simple, and very untested, but straightforward enough that it is fairly likely to work.
`GET /api/settings` returns a dictionary of key/value pairs for this user.
`POST /api/settings` takes a dictionary of key/value pairs, and inserts/updates them in this user's settings.
`DELETE /api/settings/{key}` removes the specified key from the user's settings.
Also: fixes a bug with the DuckService, which wasn't preloading its cache, and therefore was spuriously returning an empty set.
Also: a bit of refactoring to make it easier to declare functions that only work for logged-in users.
Fixes #147
> Add backend for Settings

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/DiscordController.scala
- arisia-remote/app/arisia/controllers/ScheduleTestController.scala
- arisia-remote/app/arisia/general/DiscordService.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/app/arisia/views/addTestScheduleItem.scala.html
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/conf/application.conf
- arisia-remote/conf/routes
- arisia-remote/conf/secrets.conf.template
This introduces a new Admin UI, that allows you to input fake program items. These exist only in-memory for the duration of this server run, and get merged into the real schedule. The point of this is to allow us to test actually *using* the schedule, with program items coming up in the near future, to ensure that things actually work as intended.
Also includes the very beginnings of backend-side Discord integration: so far, just a proof of concept that we can fetch the members of the Arisia Discord server. This will form part of the ArisiaBot, sharing the responsibilities with the Python Lambda bits.
> Beginnings of the Schedule Test system

- arisia-remote/app/arisia/admin/RoomService.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/models/ZoomRoom.scala
- arisia-remote/app/arisia/views/editRoom.scala.html
- arisia-remote/app/arisia/views/manageZoomRooms.scala.html
- arisia-remote/conf/evolutions/default/8.sql
- arisia-remote/conf/secrets.conf.template
If we want to be able to post automated messages, we need to be able to track how the channels correspond to the rooms.
Also, this adds the U in CRUD for the Zoom Room editing. This serves as a model for how to do that.
> Add Discord channels to the panel rooms

- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/views/errorPage.scala.html
- arisia-remote/conf/evolutions/default/10.sql
Fixes a bug in the handling of prep session urls.
Introduces a rudimentary 404 page if you try to go into a meeting that isn't running (or which you can't access).
Makes Gail into a superadmin.
Fixes #262 
Fixes #263
> Get Zoom meeting entry basically working

- frontend/src/app/_services/account.service.ts
The first bug was that we never subscribed to the "me" call in
account.service.ts. Switching from a tap to a subscribe fixed
that. The other calls currently have subscribers, but I'm going to
learn how to multicast Observables so that we can trigger the
login/logout even if the caller doesn't subscribe.
The second bug was that user$ and loggedIn$ both returned a value
before we got the response from me. This meant that we redirected to
the login page before we were able to check if we were already logged
in.
> Fix login bugs.

- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/conf/application.conf
This now actually sets the user info in the DB when you log in, so that we can associate the Discord info with it.
This now loads the Arisia Discord server's member list properly, paginating the way the Discord API wants you to do.
We cache the member list, in the hope that we will sometimes be able to use the cached info instead of having to load the whole bloody thing.
We store the discord information in the user_info table for later access.
In theory, we set your Discord nickname to your badge name; that isn't working for me, but I suspect that's because I'm a Server Admin.
> Continuing to build the Discord API

- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/controllers/DiscordController.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/conf/application.conf
- arisia-remote/conf/evolutions/default/11.sql
- arisia-remote/conf/routes
- arisia-remote/conf/secrets.conf.template
This provides two new entry points:
* `GET /api/discord/getAssistSecret` returns a secret that a user can use in order to seek help getting set up with Discord.
* `POST /api/discord/assistAddArisian` allows Help Desk to provide assistance.
The latter entry point requires a `X-Shared-Secret` header, since it is intended solely for the use of Lambda. (Gail and Justin will agree on a secret for production, which goes into secrets.conf.)
It takes the following data structure:
```
{ "badgeNumber": "1111", "secret": "xxxx", "discordId": "30940493039303930" }
```
The secret comes from the other entry point, and validates the user. The Discord ID comes from the slash comment that Help Desk uses.
Includes an enhancement to store the Badge Name in the DB, which had previously been overlooked.
Fixes …
> Assisted Discord setup API

- arisia-remote/app/arisia/controllers/LoginController.scala
- frontend/src/app/_services/account.service.ts
The existing path was causing the frontend to fall back to defaults, resulting in a rash of people showing up as "Joe". This should make it easier to get that behavior right.
> Fix /api/me to return Unauthorized if you're not logged in.

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/AdminControllerFuncs.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/FileController.scala
- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/general/FileService.scala
- arisia-remote/app/arisia/general/FileType.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/uploadMetadata.scala.html
- arisia-remote/conf/routes
- frontend/src/app/_services/account.service.ts
This provides a new, fairly general-purpose mechanism whereby we can add Admin UI for uploading specific text files, and API entry points so that the frontend can fetch them.  For now, it is implemented for Art Show and Dealers metadata, but we can easily add more file types as needed -- at this point, it's something like 1-2 dozen lines of code to add another type.
The new entry points are:
```
GET /api/metadata/artshow
GET /api/metadata/dealers
```
Fixes #114
> Metadata management

- arisia-remote/app/arisia/admin/AdminService.scala
- arisia-remote/app/arisia/auth/CMService.scala
- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/fun/DuckService.scala
- arisia-remote/app/arisia/general/SettingsService.scala
- arisia-remote/app/arisia/models/LoginUser.scala
- arisia-remote/app/arisia/schedule/StarService.scala
CM is case-insensitive. We aren't. That's a problem, and has caused a few snags. This tweaks the database code accordingly, by lowercasing the username across the board.
(It's a tad more ad-hoc than I'd like, but at this point it's probably the least-risk approach.)
Fixes #220
> Deal with case sensitivity in usernames

- arisia-remote/app/arisia/GeneralModule.scala
- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/AdminControllerFuncs.scala
- arisia-remote/app/arisia/controllers/ControllerModule.scala
- arisia-remote/app/arisia/controllers/FileController.scala
- arisia-remote/app/arisia/controllers/ScheduleTestController.scala
- arisia-remote/app/arisia/general/FileService.scala
- arisia-remote/app/arisia/general/FileType.scala
- arisia-remote/app/arisia/models/ProgramItem.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/uploadMetadata.scala.html
- arisia-remote/conf/routes
This adds two new fields to program items with Zoom.  `doorsOpen` is the timestamp to start showing the entry links; `doorsClose` is when to stop.  (Note that doorsOpen is intentionally five minutes before the actual panel start time.)
The intent is to make it easier for the front end to show the links at the right times -- hopefully it's helpful.
For some reason, this PR is stupidly over-large: we seem to be having rebase problems.  Sorry about that.
Fixes #255
> Add door times

- arisia-remote/app/arisia/controllers/LoginController.scala
- arisia-remote/app/arisia/fun/DuckService.scala
- arisia-remote/conf/routes
- build.sbt
This adds two new entry points:
```
GET /api/user
GET /api/user/:id
```
The first one fetches your own profile info, the second someone else's.  Both are only available to logged-in users.
Fixes #306 -- the returned data structure should match the spec in there.  Note that some of that isn't properly tested yet (in particular, the duck list): yell if you find problems.
> Profile Support

- arisia-remote/app/arisia/controllers/DuckController.scala
- arisia-remote/conf/routes
This adds a new entry point:
```
DELETE /api/ducks/:id
```
If the user is logged in, it returns 204 (NoContent).
Fixes #327
> Expose the dropDuck() function to the frontend

- arisia-remote/app/arisia/controllers/FileController.scala
- arisia-remote/app/arisia/general/FileType.scala
- arisia-remote/app/arisia/views/uploadMetadata.scala.html
- arisia-remote/conf/routes
This adds:
```
GET /api/metadata/gaming
GET /api/metadata/events
```
as well as the associated upload UI in Admin.
Fixes #314
> Add upload and get entry points for Gaming and Events metadata

- arisia-remote/app/arisia/controllers/FrontendController.scala
- arisia-remote/conf/application.conf
- arisia-remote/conf/routes
This provides a new entry point:
```
GET /api/config/:name
```
Assuming that that value is in the backend config, it will return 200 with the value as the body. If the name is not known in the backend config, it will return 404.
In the backend config, the subtree `arisia.frontend` has been set aside for this purpose -- the frontend team are encouraged to put their values in there. The real values should go into secrets.conf; I recommend documenting those entries in secrets.conf.template and maybe application.conf, but that is not required.
So if, say, there is a backend config entry named `arisia.frontend.thingy`, you can call `GET /api/config/thingy` to fetch it.
Fixes #328
> Provide config for the frontend

- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/AdminControllerFuncs.scala
- arisia-remote/app/arisia/controllers/DiscordController.scala
- arisia-remote/app/arisia/controllers/DuckController.scala
- arisia-remote/app/arisia/controllers/FileController.scala
- arisia-remote/app/arisia/controllers/ScheduleTestController.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
It ain't fancy, but it at least shows us any time an Admin is poking around, and what they are doing.
Coded such that you *have* to have auditing if you are following the standard Admin UI controller patterns, to prevent accidentally forgetting an entry point. This means that even looking at Admin pages will be audited -- not a bad thing on general principles.
Fixes #145
> Add a simplistic Admin Audit Trail

- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/models/ProgramItem.scala
- arisia-remote/app/arisia/models/Schedule.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
If someone is a program participant and *not* a potential host, show they a custom schedule that contains only their prep sessions.
Fixes #215
> Customized schedule for program participants

- arisia-remote/app/arisia/admin/RoomService.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/views/editRoom.scala.html
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/conf/routes
(Draft: there is time to change this, but let's be concrete about it.)
We have a lot of Zoom spaces that are *not* scheduled (eg, Gaming, Social, Youth), and so don't fit into the framework so far. These meetings are owned by their respective divisions, who will be empowered to open and close the rooms when they see fit. (We will use the "personal meeting" attached to each account, because that is by far the easiest way to deal with it.)
So this adds two new entry points to allow the frontend to allow users into those rooms when appropriate:
```
GET /api/room/open/:name
GET /api/room/enter/:name
```
In both cases, we will agree on the value of `name` -- probably something like `gaming`, `social`, etc. (The backend values are configured in the Admin UI, so the UI can set what it likes.) …
> Backend hooks for working with "manual" meetings

- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/controllers/DiscordController.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/conf/evolutions/default/12.sql
- arisia-remote/conf/routes
This is the third backend story for Discord. Adds a new entry point:
```
PUT /api/discord/sync/:id
```
Note that the `X-Shared-Secret` header must be set: this is intended only for use from Lambda.
The `:id` should be the Discord ID of a member who has already connected from Virtual Arisia to Discord. It will resync their info -- in practice for now, it resyncs their Badge Name.
Not well-tested, because it is unfortunately difficult to use my Discord account for testing. (Since I'm a Site Admin, bot changes to me tend to be rejected by Discord.)
Fixes #284
> Add Discord Sync

- arisia-remote/conf/application.conf
We hit a weird error on production when trying to upload a 145k file. It looks like this *could* happen from Play (although it hasn't been doing so in Dev). This adds a couple of config values that should raise the limit to 10MB, if that's where the problem is coming from.
> Lift upload limits

- arisia-remote/app/arisia/auth/MembershipType.scala
- arisia-remote/app/arisia/controllers/FileController.scala
- arisia-remote/app/arisia/general/FileType.scala
- arisia-remote/app/arisia/views/uploadMetadata.scala.html
- arisia-remote/conf/routes
This provides the upload and download for the Coffee Shop Line metadata, same as for the other metadata types.
Also, adds the CMPMSC MembershipType, which we turn out to need.
Fixes #313
> Manage Coffee Shop Line metadata

- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/restartMeeting.scala.html
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/conf/routes
There is a failure mode we have to deal with: the Host does the wrong thing, and shuts down a program item prematurely. At that point, the Zoom meeting is dead -- everyone is kicked out, and nobody (including the Host) can re-enter.
So this adds a new Admin UI page for this emergency. Give it the item number for a program item in this state, and it will properly close the original version, start up a new meeting, and rewire everything. At that point, the Host can re-enter, and then the participants.
Fixes #265
> Provide a way to restart meetings

- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/app/arisia/zoom/models/ZoomMeeting.scala
- arisia-remote/conf/evolutions/default/13.sql
While Zoom's API is mostly nice, it does have a deep stupidity that the entry points for Meetings and Webinars are completely unrelated, even though they do almost exactly the same things.
So this propagates through the concept of whether a given program item is a Webinar or not, and calls the appropriate entry points depending on the answer.
Fixes #217
> Get Webinars working

- arisia-remote/app/arisia/auth/CMService.scala
- arisia-remote/app/arisia/auth/LoginError.scala
Instead of sending an enumeration to the frontend on login failure, we send the full text to render.
This also adds another error case: this user's password has expired, so they need to go to Registration to fix it.
Fixes the backend side of #369, but the frontend needs to pick that up and show the messages.
> Better login errors

- arisia-remote/app/arisia/controllers/ScheduleController.scala
- arisia-remote/app/arisia/timer/TimerService.scala
- arisia-remote/conf/logback.xml
This makes My Schedule much more useful for program participants: they don't have to go find and star their stuff manually.
Also, turned logging down slightly, to reduce log spam. (In particular, the Timer no longer spams the log by default.)
Fixes #370
> Pre-star program items where I am a participant

- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/test/arisia/discord/DiscordServiceSpec.scala
Instead of the unchecked fake secret (which allowed abuse), this replaces it with something that is decently cryptographically sound. Requires the user to copy/paste (it's too long to retype), but Gail indicated that was okay.
Fixes #298
> Put a real secret in place for the assisted-Discord flow

- arisia-remote/app/arisia/controllers/ScheduleController.scala
We were basing the stars on the basic schedule; should be the full schedule.
> Need the prep sessions to show up on My Schedule as well

- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/test/arisia/discord/DiscordServiceSpec.scala
Going to a somewhat less-secure (but still probably good enough) hash, and switch from hex to base64, to bring down the length of the resulting string.
> Switch the security encoding

- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/showMeetingUrl.scala.html
- arisia-remote/app/arisia/views/showMeetingUrlInput.scala.html
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/conf/routes
We need to be able to get the magic Start URLs for the manually-managed meetings, so that people other than the account owner can start them. This provides an admin interface that, given the standardized name for the meeting (eg, "social"), hands you back the Start URL, which can be used immediately or shared around.
> Get Manual Meeting Start URLs

- arisia-remote/app/arisia/controllers/ScheduleTestController.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
This mechanism was created for my own test purposes, and I still need it for that in local dev. But it causes problems on the live site, so we shouldn't be allowing people to use it.
This should be merged later this evening, once Tech is done with training.
> Restrict access to test meetings

- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/discord/discord.component.html
- frontend/src/app/discord/discord.component.scss
- frontend/src/app/discord/discord.component.ts
Also improves Display button behavior if download takes a while.
Should disappear if copying isn't supported, but that's untested.
> Add Copy button to discord secret.

- arisia-remote/app/arisia/controllers/ScheduleController.scala
Fixes a problem Chris pointed out several days ago, which I failed to find time to investigate. This should solve the problem when people are added/removed as Tech during the con -- it produces a different ETag in those situations.
(I believe it's a non-issue when someone's Program Participant status changes: that implies a change to the Schedule, so the ETags will be invalidated anyway.)
Fixes #341
> Separate ETags for Hosts from those for everyone else

- arisia-remote/app/arisia/auth/MembershipType.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/conf/application.conf
We are getting rate-limited on the load-members call. So switching that to poll every five minutes, instead of doing it on demand.
Hopefully this works -- we're all clogged up now, so I can't properly test.
Also add the Adult Rollover membership type.
Fixes #389 
Fixes #428
> Hopefully a fix to the Discord rate limiting

- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/schedule/ScheduleService.scala
- arisia-remote/conf/application.conf
Fast Track is a funny case: unlike most of our programming, with individually-created meetings for everything, it's just a breakout room in Youth Services.
So this little hack intercepts all attempts to enter Fast Track panels, and instead routes them to the Youth Services Zoom. Not the prettiest thing in the world, but it ought to work.
This requires some configuration on the live site, to hook the pieces together; I will deal with that after we deploy this.
Fixes #408
> Redirect FastTrack panels into the Youth Services Zoom

- arisia-remote/conf/application.conf
Somehow, I had gotten the idea that Fast Track had the location "FastTrack Zoom" in Zambia, but that appears to not be correct. Fixing this to detect the right sessions.
> Fix the Fast Track link

- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
It looks like the ur-cause of the duplicate meetings that have been plaguing us today is the _scheduleCursor, which keeps track of where we are in the Schedule. Which is great in theory, but we were never actually *updating* that cursor in-memory, because I was tired and dumb.
On its own, this was innocuous, because we pull things off the front of the Schedule Queue as we start them. But whenever the Schedule *changes* (which it does fairly often), we would regenerate the whole queue, completely fail to remove the stuff that was already started (because we weren't updating the cursor), and restart all of these already-existing meetings. Hence, bazillions of duplicates.
This fixes that with the one-liner to actually update the cursor where we should have been doing all along.
We also add a …
> Fix The Incredibly Stupid Cursor Bug

- arisia-remote/app/arisia/auth/CMService.scala
- arisia-remote/app/arisia/auth/LoginService.scala
- arisia-remote/app/arisia/discord/DiscordService.scala
- arisia-remote/app/arisia/models/LoginUser.scala
The (pretty old) CM-webscrape code defaulted, if you didn't have a Badge Name, to using your username. That seemed to make sense at the time, since the username is the primary key to everything, but it needs to be treated as potential PII, because *that* appears to often be peoples' email address. And that problem becomes Much Worse because we change peoples' Discord nickname to be their Badge Name.
So this just turns off that defaulting, and if the Badge Name is empty, doesn't touch the Discord nickname.
Fixes #461
> Fix PII leak for users without Badge Names

- arisia-remote/app/arisia/controllers/AdminController.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
This *may* fix the problem with that page -- certainly it fixes *a* problem with it. (We were previously fetching the prep sessions, but trying to look up the real sessions. I don't know why that was occasionally working: it should have always failed.)
Fixes #463
> Provisional fix for Show Currently Running Meetings

- arisia-remote/app/arisia/controllers/ScheduleController.scala
If you logged in as a program participant, and you had previously looked at the Schedule, and it hadn't changed in Zambia, you would still see the logged-out view without your prep sessions. This fixes that, by distinguishing the logged-out ETag.
(Yes, it's a conceptually ugly fix, but it's easy, safe, and works.)
Fixes #466
> Fix caching when switching from logged-out to logged-in

- arisia-remote/app/arisia/auth/LoginService.scala
It looks like you can log in with a space before or after your name, and CM silently allows that. (User 96704 apparently did so.) The result is that they have duplicate entries in user_info. That was causing database errors, which in turn (I suspect) means that their Profile Page was broken.
Ideally we would fix the login pathway, but for now the safer approach is to simply tolerate it.
Fixes #469
> Fix Profile Page for people who have duplicate login entries

- arisia-remote/app/arisia/controllers/ZoomController.scala
- arisia-remote/app/arisia/schedule/ScheduleQueueService.scala
- arisia-remote/app/arisia/views/adminHome.scala.html
- arisia-remote/app/arisia/views/restartMeeting.scala.html
- arisia-remote/app/arisia/zoom/ZoomService.scala
- arisia-remote/conf/routes
We have a "restart meeting" option, but that's too limited: it only works with meetings that are currently running, but for some reason we can't get to.  (Mainly for when the Zoom Host accidentally kills the meeting.)
This adds two blunter and more commonly-useful hammers:
* Force-start takes any meeting ID, and immediately starts that meeting in its assigned room.  At that point, the usual Join Meeting links should start working.  (This is for when the meeting start failed for some reason.)
* Force-stop takes any meeting ID, and slams it shut.  This is mainly intended for cases where auto-stop failed, and it's just gumming up the database.  (That has been happening a lot, so this is a workaround.)
Fixes #478
> Force start/stop
